spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mycar-business
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_URL}